name: Android Build & Release

on:
    push:
        branches: [main] # or your default branch name
    pull_request:
        branches: [main]

jobs:
    android-build:
        name: Android Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '11'

            - name: Install dependencies
              run: |
                  yarn install

            - name: Cache Gradle Wrapper
              uses: actions/cache@v2
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

            - name: Cache Gradle Dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}

            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew

            - name: Build Android Release
              run: |
                  cd android
                  ./gradlew assembleRelease

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: app-release
                  path: android/app/build/outputs/apk/release/app-release.apk

            - name: Create Release
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: softprops/action-gh-release@v1
              with:
                  files: android/app/build/outputs/apk/release/app-release.apk
                  tag_name: v1.0.${{ github.run_number }}
                  name: Release v1.0.${{ github.run_number }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
